ministryofjustice/hmpps-electronic-monitoring-create-an-order-api

helm_deploy/hmpps-electronic-monitoring-create-an-order-api/values.yaml
Certificates created in these pull requests:
- [dev](https://github.com/ministryofjustice/cloud-platform-environments/pull/25964)
- [preprod](https://github.com/ministryofjustice/cloud-platform-environments/pull/25965)
- [prod](https://github.com/ministryofjustice/cloud-platform-environments/pull/25966)
The k8s secret that stores the certificate is the same in all environments, so the base values.yaml is updated instead of the environment specific yaml files.
=> BAU: Update the deployment to use the updated certificate

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/DeviceWearerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/DeviceWearerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/DeviceWearerControllerTest.kt
Allows setting of additional fields. Updated tests to allow invalid request bodies to be constructed.
=> Allow user to set additional device wearer fields

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/DeviceWearer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/DeviceWearerAddress.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/OrderForm.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/DeviceWearerAddressType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/DeviceWearer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/repository/DeviceWearerAddressRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/repository/OrderFormRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/DeviceWearerAddressController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/DeviceWearerAddressService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderFormService.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/DeviceWearerAddressControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderFormControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderFormServiceTest.kt
Addresses are now related to the order not the device wearer. Conceptually this is wrong, but as we're collecting information related to a order, I think this is simpler.
Uses some spring magic to make the primary address have mandatory fields without adding the same constraints for the secondary and tertiary addresses.
=> Allow a Notifying Organisation to enter addresses

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/Address.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/DeviceWearerAddress.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/DeviceWearer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/DeviceWearerAddressService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/DeviceWearerAddressControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderFormControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderFormServiceTest.kt
Addresses are required during the creation of monitoring conditions (e.g. alcohol monitoring installation address, mandatory attendance addresses) so decouple the address from the use of the address.
=> Addresses are not always related to a device wearer

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/Address.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/DeviceWearerAddress.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/DeviceWearerAddressType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/DeviceWearer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/DeviceWearerAddressController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/DeviceWearerAddressService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/DeviceWearerAddressControllerTest.kt
Changes:
- Allow a device wearer address to be flagged as no fixed abode
- Allow an address to be flagged as an installation address
- Allow an additional `INSTALLATION` address type
Future:
- There is a large possibility that addresses will end up in an "invalid" state without additional validation / checks.
=> Update addresses to enable all possible options in the frontend

.circleci/config.yml
- Created the RDS instance in this [PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/26885).
- Created a placeholder `serco-secret` with the following content to allow the application to start:
```yaml
apiVersion: v1
data:
SERCO_AUTH_URL: ""
SERCO_CLIENT_ID: ""
SERCO_CLIENT_SECRET: ""
SERCO_PASSWORD: ""
SERCO_URL: ""
SERCO_USERNAME: ""
kind: Secret
metadata:
creationTimestamp: "2024-10-15T14:43:07Z"
name: serco-secret
namespace: hmpps-ems-cemo-ui-preprod
resourceVersion:
uid: 
type: Opaque
```
=> Enable preprod deployment

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AddressService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/AddressControllerTest.kt
When updating an already existing address, the following error occurred:
```shell
Unexpected error: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call
```
Adding the `@Transactional` decorator solved this problem but introduced a new problem.
```shell
Unexpected error: could not execute statement [ERROR: duplicate key value violates unique constraint "address_order_id_address_type_key" Detail: Key (order_id, address_type)=(f53c1c81-7fa5-46c7-90e3-54818cffd3b8, PRIMARY) already exists.]
```
This occurs because the entity manager does all `inserts` before it does any `deletes`.
We get around this by flushing the entity manager after the delete and before the insert.
=> Allow an address to be updated multiple times

.circleci/config.yml, helm_deploy/values-preprod.yaml
This is a temporary change to deploy an additional copy of the api to the `dev` namespace. This works by removing the reference to the preprod circleci context which contains the values needed to configure helm to deploy to preprod. 
Adjusting the default `release_name` to `PROJECT_NAME_ENV_NAME` should result in there being 2 distinct k8s deployments within the namespace `hmpps-electronic-monitoring-create-an-order-api` (dev) and `hmpps-electronic-monitoring-create-an-order-api-preprod` (preprod).
By deploying the preprod environment to the dev namespace, the preprod environment will use the dev secrets for `hmpps-auth` where we have greater control of user management (allowing us to create test users for UAT).
=> Deploy the preprod api to the dev namespace

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/Address.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateAddressDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateInterestedPartiesDto.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/InterestedPartiesControllerTest.kt
Feedback from product owner is that all interested party fields are optional.
- Addresses can now be stored with empty strings for all values (addressLine1, addressLine2, ... , postcode) therefore allowing us to create the responsible organisation address without the user having to provide values.
- The `UpdateAddressDto` does validation for all other addresses, (primary, secondary, tertiary, installation) ensuring that they remain valid when created by the end user.
=> Responsible organisation address fields are optional

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateMonitoringConditionsDto.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/MonitoringConditionsControllerTest.kt
Adds a missing update from [#84 update start dates to allow historic dates](#84 )
=> Remove outdated monitoring conditions startDate validation

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/criteria/OrderSearchCriteria.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/specification/OrderSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/repository/OrderRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/OrderController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resources/OrderControllerTest.kt
- Implements searching for orders by `order.deviceWearer.firstName`
- Implements searching for orders by `order.deviceWearer.lastName`
- Searching is case insensitive
- Implements the search functionality using the [Spring JPA Specifications](https://docs.spring.io/spring-data/jpa/reference/jpa/specifications.html) to allow creation of more complex predicates than the normal repository methods would allow.
- Works with the existing UI implementation because `searchTerm` is optional in the controller and within the specification.
=> Add the ability to search for orders by firstName and lastName

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/Order.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/CreateOrderDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/OrderType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/OrderController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/courthearing/HearingEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/AdditionalDocumentsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/EnforcementZoneControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/repository/OrderRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resources/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AdditionalDocumentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AddressServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/MonitoringConditionsAlcoholServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderServiceTest.kt
- Adds the `type` property to an order
- By default orders are created with the `REQUEST` type
- Therefore doesn't break the existing user interface 
- Disables submission of variations until integration is implemented 
- Also refactored OrderController test suite to group tests by functionality / endpoint as they were becoming a bit unclear, e.g.
```text
DELETE /api/orders/{orderId}
Test It should delete an in progress order() PASSED
Test It should return an error if the order is in a submitted state() PASSED
Test It should return an error if the order does not exist() PASSED
Test It should return an error if the order belongs to another user() PASSED
GET /api/orders/{orderId}
Test It should return not found if order belongs to another user() PASSED
Test It should return not found if …
```
=> Initial implementation of create a variation

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/CurfewConditions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/DeviceWearer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/MonitoringOrder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/courthearing/HearingEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderServiceTest.kt, src/test/resources/json/CCSIB_BAIL_EXCLUSION/expected_fms_order.json, src/test/resources/json/CCSIB_Crown_Court_BAIL_EXCLUSION/expected_fms_order.json, src/test/resources/json/COEW_AAR/expected_fms_order.json, src/test/resources/json/COV_Community_Order_Trail/expected_fms_order.json, src/test/resources/json/CommunityOrder_Curfew/expected_fms_order.json, src/test/resources/json/RC_BAIL_INCLUSION/expected_fms_order.json, src/test/resources/json/REMCB_BAIL_CURFEW/expected_fms_order.json, src/test/resources/json/RIB_BAIL_EXCLUSION_EXCEPT_COURT_OR_APPOINTMENT/expected_fms_order.json, src/test/resources/json/RILAB_BAIL_INCLUSION/expected_fms_order.json, src/test/resources/json/SSO_IMPRISONMENT/expected_fms_order.json, src/test/resources/json/SSO_YOUNG_OFFENDER_INSTITUTION_DETENTION/expected_fms_order.json
Ticket: https://dsdmoj.atlassian.net/browse/ELM-3101
The following changed made to reflect Serco api schema change for v5 - Dec 2024:
- enforceable_condition now has start_date and end_date fields, example:
```
{
"condition": "EM Exclusion / Inclusion Zone",
"start_date": "2024-11-27 07:00:00",
"end_date": "2024-12-27 07:00:00"
}
```
- Added text field curfew_description
- exclusion_zones and inclusion_zones is now a list object , example:
```
"exclusion_zones": [
{
"description": "Zone 1",
"duration": "Mon-Fri 10-22",
"start": "28/11/2024",
"end": "28/12/2024"
},
{
"description": "Zone 2",
"duration": "Mon-Fri 11-23",
"start": "28/11/2024",
"end": "28/01/2025"
}
]
"inclusion_zones": [
{
"description": "Zone 3",
"duration": "Mon-Fri 10-22",
"start": "28/11/2024",
"end": "28/12/2024"
},
{ …
```
=> Elm 3101 serco v5 dec 2024 changes

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/Order.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/VariationDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateVariationDetailsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/VariationType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/VariationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/VariationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/VariationControllerTest.kt
This sets up a new controller for variations with a simple put endpoint for creating / updating variation details.
The DTO receives the variationType and variationDate as simple string values and then validates that they can be parsed to the correct type during validation. The alternative would be to allow the framework to cast them to the desired datatypes (`Enum` / `ZonedDateTime`), however this can generate `HttpMessageNotReadableException` exceptions if either of the fields are missing or contain invalid values (e.g. a bad datetime string) and wouldn't allow us to generate client friendly validation error messages.
=> Allow creation / updates to variation details

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/client/FmsClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/wiremock/SercoMockApi.kt
The current serco url secret contains the path `api/x_seem_cemo/`. This change adds the `x_seem_cemo/` to the createDeviceWearer, createMonitoringOrder, updateMonitoringOrder endpoints and adds `now/v1/` to the attachments endpoint so that the secret can be used for all integration endpoints.
The secret has been updated in dev to remove `x_seem_cemo/`
=> Update the paths used in integrations with Serco

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/strategy/FmsOrderSubmissionStrategy.kt
When setting up the cypress tests for CEMO014 which sends enforcement zone documents to the Field Monitoring Service, the resulting order could not be parsed by the front end.
The implementation for sending enforcement zone documents to Serco involved adding the enforcement zone documents to the list of additional documents. This accidentally mutated the order which was then saved creating an order that could not be parsed by the front end. 
This change forces a shallow copy of the `additionalDocuments` rather than using the reference to the existing object, thus solving the mutation problem.
=> Fix problems with mutating the order during submission

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/MonitoringConditions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/Order.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/CreateOrderDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateMonitoringConditionsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/OrderType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/RequestType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/MonitoringOrder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/FmsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/courthearing/HearingEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/AdditionalDocumentsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/EnforcementZoneControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/MonitoringConditionsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/repository/OrderRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resources/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AdditionalDocumentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AddressServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/MonitoringConditionsAlcoholServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderServiceTest.kt
- Changed `OrderType` enum-> `RequestType` to reflect it use internally within the system
- Add `OrderType` enum to ensure requests to Serco use the values specified in the JSON mapping spreadsheet
=> Make order type an enum with the correct values

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/DeviceWearer.kt
#160 changed the required address fields from:
- addressLine1
- addressLine2
- postcode
to:
- addressLine1
- addressLine3
- postcode
This change updates the mapping to the FMS Device Wearer request to ensure valid requests are generated.
=> Update address mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/FmsSubmissionResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt
Update API to return additional error message when partially successful creating Serco request( successful create Device Wearer and Monitoring order, but failed to create attachments)
=> Add partial success check for fms submit result

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/data/ValidationErrors.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateInstallationAndRiskDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/RiskCategory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/InstallationAndRiskControllerTest.kt
- Ensure that we only capture valid risk categories as defined in DDv4.1
- Two options will not be captured by the CEMO API:
- "Offence Risk"
- "Postcode Risk"
=> Validate risk categories

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/data/ValidationErrors.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateInstallationAndRiskDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/Offence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/MonitoringOrder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/InstallationAndRiskControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderServiceTest.kt
- Ensure that we only capture valid offences as defined in DDv4.1
- Update the mapping of offences when sending to Serco
=> Validate offence

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateInstallationAndRiskDto.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/InstallationAndRiskControllerTest.kt
#176 accidentally made the offence field mandatory in the UI as it sends an empty string if no option is selected. This ensures that offence is optional.
=> Make sure that offence is optional i.e. an empty string

helm_deploy/hmpps-electronic-monitoring-create-an-order-api/values.yaml
The default modsecurity policy blocks `PUT` and `DELETE` requests that are used in the API. This is preventing the UI from sending requests.
For future reference the default snippet is here: https://github.com/ministryofjustice/hmpps-helm-charts/blob/9b8a897760449cc2f97b7d6f662c0e77c4e34a8f/charts/generic-service/values.yaml#L69
Other services have faced the same problem and overriden the default snippet: https://github.com/ministryofjustice/hmpps-prisoner-location-api/blob/306c51d780001aeff3b61ec268b78eeab253a861/helm_deploy/hmpps-prisoner-location-api/values.yaml#L23
This requires more thinking time than I have now, so needs to be revisited.
=> Disable modesecurity waf

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/client/FmsClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/strategy/FmsVariationSubmissionStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/wiremock/SercoMockApi.kt
Serco have updated their guidance for creating variations. Any variation to an order should use the updateDW endpoint. This tells Serco that it is a service request to an existing order and will trigger the appropriate operational processes. 
Because the service allows a user to create a variation "from scratch" (i.e. not linked to an order created through the CEMO service), we have concerns that a user could create a variation for an order that does not exist in the CEMO service and also Service Now. Serco have assured us this is not a problem and to send all variations to the updateDW endpoint.
=> Update variations to send requests to updateDW

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/DeviceWearerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/DeviceWearerControllerTest.kt
Bug description in ticket.
- Test added to replicate observed behaviour and prevent regressions
=> ELM-3431: Prevent identity numbers being overwritten when updating the device wearer

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/client/FmsClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/client/FmsClientTest.kt
Based on observations from integration testing with Serco, the ServiceNow api returns errors with bodies that look like:
```json
{
"error": {
"message": "",
"detail": ""
},
"status": ""
}
```
Its very likely that not all errors will look the same, i.e. a 503 is likely to have a different body from a 500. We don't have examples of all responses at the moment so handling everything the same. Tests added for the two error responses we have observed (403/500).
=> Handle 4xx errors when sending requests to Serco

src/main/resources/application.yml, src/main/resources/db/migration/V1__Initial_Tables.sql, src/test/resources/db/migration/V1_0_0__create_ORDER_FORM_table.sql
Up to now, we've relied on Spring JPA to create and update our database schema. This has allowed us to move quickly and change the database schema to suit changing requirements. To accomplish this, we set `spring.jpa.hibernate.ddl-auto` to `create`. This mode will create the schema, destroying any previously saved data in the process.
Now that we're getting ready to launch the service, we want to retain any saved data between deployments, forcing us to change the `ddl-auto` mode we use. The two most sensible looking options are:
- `validate`: Validate the underlying database schema against the entity mappings.
- `none`: Disables the `hbm2ddl.auto` tool.
The other options are listed below have been rejected because of their possibility to modify / delete data either accidentally or without …
=> Setup database initialisation

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/MonitoringOrder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/model/fms/MonitoringOrderTest.kt
I misunderstood the purpose of the startTime and endTime properties of the attendance monitoring conditions. They indicate the start time and end time of the appointment rather than the start / end time of the attendance monitoring. i.e. the appointment is from 12:00 -> 1300 on a Monday but the appointment runs every monday from 01-01-2025 until 01-02-2025.
The start time / end time are now present in the description rather than the end and start fields.
=> Update attendance monitoring mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/strategy/FmsOrderSubmissionStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt
When an order fails to be submitted to Serco, we create a submission result entry in the database. Unfortunately, the error messages that we record, always end up being:
```text
java.lang.Exception: Failed to submit FMS Device Wearer
``` 
or 
```text
java.lang.Exception: Failed to submit FMS Monitoring Order
```
This makes them essentially useless for investigating why an order was rejected. For example, as part of testing whether a phone number was mandatory, the only way to observe the error message was to add a breakpoint in the submission strategy. This won't be possible in a production environment so we need some way of making those errors more observable.
This change ensures that the value written to the database contains the value that Serco/ServiceNow returns.
e.g.
```text
Error …
```
=> Make submission errors observable

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/MonitoringOrder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/CurfewConditionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/EnforcementZoneService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/MonitoringConditionsAlcoholService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/MonitoringConditionsTrailService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderSectionServiceBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/CurfewConditionControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/EnforcementZoneControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/MonitoringConditionsAlcoholControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/MonitoringConditionsTrailControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/MonitoringConditionsAlcoholServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderSectionServiceBaseTests.kt
This is Step 1 of [ELM-3733](https://dsdmoj.atlassian.net/jira/software/c/projects/ELM/boards/1659?selectedIssue=ELM-3733)
Changes included:
Remove defaulting for start date, UI does not capture start time for monitoring condition types, therefore it is defaulted to 00:00:00 already. 
Refactor end date defaulting to use Europe/London timezone, so it will be stored as 23:59:00 in Europe/London for the date captured in UI and will display the end date as per user input.
Update FMS mapping to use getBritishDateAndTime for monitoring condition type end date mapping so Serco will received 23:59:00 as time on the end date
Please note this is interim fix while we implementing the proposed long term fix detailed in [ELM-3733](https://dsdmoj.atlassian.net/jira/software/c/projects/ELM/boards/1659?se …
=> ELM-3733: Step 1 rollback start date defaulting and default end date to Europe/London timezone

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/data/ValidationErrors.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateVariationDetailsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/VariationType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/VariationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/VariationControllerTest.kt
Ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/ELM/boards/1659?selectedIssue=ELM-3679
Added support for DDv5 Variation types.
Mark DDv4 variation types obsolete based on feature flag
=> Support DDv5 Variation types

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/data/ValidationErrors.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateMonitoringConditionsDto.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/MonitoringConditionsControllerTest.kt
This PR adds validation of the now-mandatory End Date field of the Monitoring Conditions section.
This complements validation added to the frontend [in this PR](https://github.com/ministryofjustice/hmpps-electronic-monitoring-create-an-order/pull/371).
=> Validate the mandatory End Date field of the Monitoring Conditions section

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/RiskCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/DeviceWearer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/model/fms/DeviceWearerTest.kt
Add NO_RISK to risk category enum and not map this option to Serco
=> ELM-3742: split risk categories into two section in UI

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/criteria/OrderListCriteria.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/specification/OrderListSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/specification/OrderSearchSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/OrderController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resources/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/OrderServiceTest.kt
Add an search order endpoint to use on the frontend
List order endpoint needs some cleaning up but can do that later
Search endpoint only returns submitted orders
=> Add order search endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/DeviceWearerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/DeviceWearerServiceTest.kt
Ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/ELM/boards/4473?selectedIssue=ELM-3985
Clear device wearer responsible adult when update device wearer record adultAtTimeOfInstallation is set to true
=> ELM-3985: clear responsible adult when update device wearer

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/data/ValidationErrors.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/Order.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/OrderParameters.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/OrderVersion.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/OrderDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateHavePhotoDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/AdditionalDocumentsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resource/OrderController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AdditionalDocumentService.kt, src/main/resources/db/migration/V14__Add_Order_Parameter_Table.sql, src/main/resources/db/migration/V14__Add_Order_Parameters_Table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/AdditionalDocumentsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resources/AdditionalDocumentsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resources/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AdditionalDocumentServiceTest.kt
Create a new Order Parameters table
Backend changes required for: https://dsdmoj.atlassian.net/browse/ELM-3425
This will be used any time we need a "yes" "no" page in the frontend that will lead to future pages being / not being rendered
I have also added an endpoint to update the "havePhoto" boolean which will be used in the new additional documents flow
When the user changes from "yes" to "no", the photo attachment is deleted
=> Add order parameter table and update have photo

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/AdditionalDocumentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/AdditionalDocumentsControllerTest.kt
Delete the document from FMS when switching answers
Before we were just deleting the record from the DB and so there would be an orphan document in the file store
=> delete the document when changing answers

README.md, scripts/create-env.sh, src/main/resources/application-local.yml
Use dev url for **document management api** when running locally
Update .env script for document management api secrets
=> Update README for running backend locally

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/MonitoringConditions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/dto/UpdateMonitoringConditionsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/enums/Pilot.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/models/fms/MonitoringOrder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/listener/CourtHearingEventListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/MonitoringConditionsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/resource/OrderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/integration/scenarios/ScenarioTests.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/model/OrderTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/model/fms/MonitoringOrderTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/repository/MonitoringConditionsRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/resources/MonitoringConditionsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/MonitoringConditionsServiceTest.kt, src/test/resources/json/scenarios/cemo002/expected_order.json, src/test/resources/json/scenarios/cemo012/expected_order.json, src/test/resources/json/scenarios/cemo016/expected_order.json, src/test/resources/json/scenarios/cemo016/order.json, src/test/resources/json/scenarios/cemo017/expected_order.json, src/test/resources/json/scenarios/cemo036/expected_order.json
Ticket: https://dsdmoj.atlassian.net/browse/ELM-4052
Changes:
Refactor pilot to use Enum
Map pilot to fms monitoring order
Refactor test to use data class comparison so we don't need to updated json filed with default value every time we add new field
=> Elm-4052: pilots

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/InterestedPartiesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppselectronicmonitoringcreateanorderapi/service/InterestedPartiesServiceTest.kt
Ticket: https://dsdmoj.atlassian.net/browse/ELM-4137
Add validation check if notifying organisation is YOUTH_CUSTODY_SERVICE and notifying organisation name doesn't exist
=> ELM-4137: make youth custody service region mandatory
